# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12oJsAyU4QbAEJAOtANaDNfc0XGNwb7N1
"""

import numpy as np
import itertools
import random
import matplotlib.pyplot as plt

# Constants
R_E = 6371  # Radius of Earth in km
c = 3e8  # Speed of light in m/s
P_transmitted = 1  # Transmitted power in W
I = 0.1  # Interference power in W
N_noise = 0.1  # Noise power in W
sigma_h = 10  # Standard deviation for altitude changes
sigma_phi = np.radians(1)  # Standard deviation for zenith angle changes in radians
alpha_lr = 0.1  # Learning rate
gamma_discount = 0.9  # Discount factor
epsilon = 0.1  # Exploration rate
num_episodes = 1000  # Number of episodes
alpha = 1.0  # Reward weight for coverage
beta = 1.0  # Reward weight for latency
gamma = 1.0  # Reward weight for SINR
N = 100  # Number of satellites

# Define state and action space
altitudes = np.arange(500, 701, 100)  # Altitudes in km
zenith_angles = np.linspace(0, np.arccos(R_E / (R_E + 700)), 5)  # Earth-centered zenith angles in radians
observer_zenith_angles = np.arcsin(np.linspace(-1, 1, 5))  # Observer-centered zenith angles in radians

# Possible changes in altitudes and zenith angles
altitude_changes = [-100, 0, 100]  # Changes in km
zenith_angle_changes = [-np.pi/12, 0, np.pi/12]  # Changes in radians
observer_zenith_angle_changes = [-np.pi/12, 0, np.pi/12]  # Changes in radians

# Create action space as combinations of possible changes

actions = list(itertools.product(altitude_changes, zenith_angle_changes, observer_zenith_angle_changes,
                                 altitude_changes, zenith_angle_changes, observer_zenith_angle_changes,
                                 altitude_changes, zenith_angle_changes, observer_zenith_angle_changes))

# Create state space as combinations of altitudes and zenith angles for three satellites
states = list(itertools.product(altitudes, zenith_angles, observer_zenith_angles,
                                altitudes, zenith_angles, observer_zenith_angles,
                                altitudes, zenith_angles, observer_zenith_angles))

# Initialize Q-values
Q = {state: {action: 0 for action in actions} for state in states}

from scipy.spatial import distance

import numpy as np
import itertools
import random
import matplotlib.pyplot as plt
num_episodes = 1000
# Check if two points have line of sight
def line_of_sight(p1, p2, R_E):
    d = distance.euclidean(p1, p2)
    return d <= np.sqrt((R_E + p1[2])**2 - R_E**2) + np.sqrt((R_E + p2[2])**2 - R_E**2)

# Find the closest satellite to a given point
def closest_satellite(point, satellites):
    return min(satellites, key=lambda s: distance.euclidean(point, s))

def find_route(A, B, satellites, R_E):
    d_tot = 0
    num_hops = 0
    current_node = A

    while True:
        los_satellites = [s for s in satellites if line_of_sight(current_node, s, R_E)]
        if not los_satellites:
            raise ValueError("No line of sight satellites found.")

        s_hat = closest_satellite(B, los_satellites)
        d_tot += distance.euclidean(current_node, s_hat)
        num_hops += 1

        if line_of_sight(s_hat, B, R_E):
            d_tot += distance.euclidean(s_hat, B)
            break

        current_node = s_hat

    return d_tot, num_hops

# Propagation delay
def propagation_delay(d, c):
    return d / c

# Reward function with routing algorithm
def compute_reward_with_routing(state, action, new_state, A, B, satellites):
    h1, phi1, phi1_prime, h2, phi2, phi2_prime, h3, phi3, phi3_prime = state
    h1_new, phi1_new, phi1_prime_new, h2_new, phi2_new, phi2_prime_new, h3_new, phi3_new, phi3_prime_new = new_state

    satellite_positions = [
        (R_E * np.cos(phi1) * np.cos(phi1_prime), R_E * np.cos(phi1) * np.sin(phi1_prime), h1),
        (R_E * np.cos(phi2) * np.cos(phi2_prime), R_E * np.cos(phi2) * np.sin(phi2_prime), h2),
        (R_E * np.cos(phi3) * np.cos(phi3_prime), R_E * np.cos(phi3) * np.sin(phi3_prime), h3)
    ]

    satellite_positions_new = [
        (R_E * np.cos(phi1_new) * np.cos(phi1_prime_new), R_E * np.cos(phi1_new) * np.sin(phi1_prime_new), h1_new),
        (R_E * np.cos(phi2_new) * np.cos(phi2_prime_new), R_E * np.cos(phi2_new) * np.sin(phi2_prime_new), h2_new),
        (R_E * np.cos(phi3_new) * np.cos(phi3_prime_new), R_E * np.cos(phi3_new) * np.sin(phi3_prime_new), h3_new)
    ]

    # Compute coverage and SINR differences as before
    coverage_old = sum(coverage(h, phi, N, R_E) for h, phi in [(h1, phi1), (h2, phi2), (h3, phi3)])
    coverage_new = sum(coverage(h, phi, N, R_E) for h, phi in [(h1_new, phi1_new), (h2_new, phi2_new), (h3_new, phi3_new)])

    L_0 = 1.0  # Example path loss parameters
    n = 2.0
    d_0 = 1.0

    path_loss_old = [path_loss(np.sqrt((R_E + h)**2 - R_E**2), L_0, n, d_0) for h in [h1, h2, h3]]
    path_loss_new = [path_loss(np.sqrt((R_E + h_new)**2 - R_E**2), L_0, n, d_0) for h_new in [h1_new, h2_new, h3_new]]

    P_received_old = [received_power(P_transmitted, pl, 1, 1) for pl in path_loss_old]
    P_received_new = [received_power(P_transmitted, pl, 1, 1) for pl in path_loss_new]

    SINR_old = [SINR(P, I, N_noise) for P in P_received_old]
    SINR_new = [SINR(P, I, N_noise) for P in P_received_new]

    # Routing and latency calculation
    d_tot_old, num_hops_old = find_route(A, B, satellite_positions, R_E)
    d_tot_new, num_hops_new = find_route(A, B, satellite_positions_new, R_E)

    latency_old = propagation_delay(d_tot_old, c) + num_hops_old * 1  # Assuming 1 second processing delay
    latency_new = propagation_delay(d_tot_new, c) + num_hops_new * 1

    reward = alpha * (coverage_new - coverage_old) - beta * (latency_new - latency_old) + gamma * (sum(SINR_new) - sum(SINR_old))
    return reward

# Q-Learning Algorithm with the updated reward function
for episode in range(num_episodes):
    state = random.choice(states)  # Initialize state randomly
    episode_reward = 0
    done = False

    while not done:
        if random.uniform(0, 1) < epsilon:
            action = random.choice(actions)  # Explore action space
        else:
            action = max(Q[state], key=Q[state].get)  # Exploit learned values

        new_state = transition_probability(state, action)

        if new_state not in Q:
            Q[new_state] = {a: 0 for a in actions}

        reward = compute_reward_with_routing(state, action, new_state, A, B, satellites)
        episode_reward += reward
        best_future_value = max(Q[new_state].values())

        Q[state][action] += alpha_lr * (reward + gamma_discount * best_future_value - Q[state][action])

        state = new_state

        # Define a stopping condition if necessary, e.g., maximum iterations within an episode
        if episode_reward < -1000:  # Example condition
            done = True

    if episode % 100 == 0:
        print(f"Episode {episode}, Reward: {episode_reward}")

print("Q-learning completed.")

# Plotting the learning curve
rewards = []

for episode in range(num_episodes):
    state = random.choice(states)  # Initialize state randomly
    episode_reward = 0
    done = False

    while not done:
        if random.uniform(0, 1) < epsilon:
            action = random.choice(actions)  # Explore action space
        else:
            action = max(Q[state], key=Q[state].get)  # Exploit learned values

        new_state = transition_probability(state, action)

        if new_state not in Q:
            Q[new_state] = {a: 0 for a in actions}

        reward = compute_reward_with_routing(state, action, new_state, A, B, satellites)
        episode_reward += reward
        best_future_value = max(Q[new_state].values())

        Q[state][action] += alpha_lr * (reward + gamma_discount * best_future_value - Q[state][action])

        state = new_state

        # Define a stopping condition if necessary, e.g., maximum iterations within an episode
        if episode_reward < -1000:  # Example condition
            done = True

    rewards.append(episode_reward)

plt.plot(rewards)
plt.xlabel('Episode')
plt.ylabel('Reward')
plt.title('Learning Curve')
plt.show()