# -*- coding: utf-8 -*-
"""third_updates_gym_Q_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-K8ui9-tg7GPMxzG9rzDThV60XJHHQfr
"""

!pip install skyfield

import gym
import numpy as np
from collections import defaultdict
import matplotlib.pyplot as plt
from gym import spaces
from scipy.spatial import distance
import random
import datetime
from datetime import timezone
from datetime import datetime

class SatelliteRoutingEnv(gym.Env):
    def __init__(self):
        super(SatelliteRoutingEnv, self).__init__()
        # x and y and Z will  be the states , action space increment and decrement postions limited alttitude  , restrictop euclidean norm is less than re+ max hight and more than re+ min height
        # Constants
        self.R_E = 6371
        self.c = 299792.458
        self.P_transmitted = 1.0
        self.N_noise = 1.0  # Noise power
        self.num_satellites = 2
        self.heights = [500, 600]
        self.phi_angles = np.linspace(0, np.pi, 40)

        self.delta_height_range = [-100, 0, 100]

        self.lats = np.linspace(-90, 90, 40)
        self.lons = np.linspace(-180, 180, 40)

        self.delta_angle_range = [-5, 0, 5]

        # Action and state spaces: heights, phi, latitude, and longitude
        self.action_space = spaces.MultiDiscrete(
            [len(self.delta_height_range)] * self.num_satellites +
            [len(self.delta_angle_range)] * 2 * self.num_satellites  # Latitude, Longitude actions for each satellite
        )






        # Action and state spaces

        self.state_space = [
            (lat1, lon1, h1, lat2, lon2, h2, lat3, lon3, h3)
            for lat1 in self.lats
            for lon1 in self.lons

            for h1 in self.heights
            for lat2 in self.lats
            for lon2 in self.lons
            for h2 in self.heights
            for lat3 in self.lats
            for lon3 in self.lons
            for h3 in self.heights
        ]

        self.observation_space = spaces.Discrete(len(self.state_space))





        # Convert Berlin and Cape Town to ECI coordinates
        self.A = self.geodetic_to_eci(52.52, 13.41)  # Berlin
        self.B = self.geodetic_to_eci(-33.92, 18.42)  # Cape Town

        self.state = None
        self.reset()

    def reset(self):
        self.state = random.choice(self.state_space)
        return self.state_space.index(self.state)

    def step(self, action):
        new_state = self.transition_probability(self.state, action)
        reward = self.compute_reward(self.state, action, new_state)

        self.state = new_state

        done = False
        if reward < -1000:  # Example cond to end episode
            done = True

        return self.state_space.index(self.state), reward, done, {}

    def transition_probability(self, state, action):
        lat1, lon1, h1, lat2, lon2, h2, lat3, lon3, h3 = state
        dh1, dh2, dh3 = self.delta_height_range[action[0]], self.delta_height_range[action[1]], self.delta_height_range[action[2]]
        dlat1, dlat2, dlat3 = self.delta_angle_range[action[3]], self.delta_angle_range[action[4]], self.delta_angle_range[action[5]]
        dlon1, dlon2, dlon3 = self.delta_angle_range[action[6]], self.delta_angle_range[action[7]], self.delta_angle_range[action[8]]


        h1_new = min(max(h1 + dh1, 500), 600)
        h2_new = min(max(h2 + dh2, 500), 600)
        h3_new = min(max(h3 + dh3, 500), 600)

        lat1_new = min(max(lat1 + dlat1, -90), 90)
        lat2_new = min(max(lat2 + dlat2, -90), 90)
        lat3_new = min(max(lat3 + dlat3, -90), 90)

        lon1_new = (lon1 + dlon1) % 360
        lon2_new = (lon2 + dlon2) % 360
        lon3_new = (lon3 + dlon3) % 360


        new_state = (lat1_new, lon1_new, h1_new,
                     lat2_new, lon2_new, h2_new,
                     lat3_new, lon3_new, h3_new)

        # Ensure new state is valid (altitude constraint)
        new_state_eci = [
            self.geodetic_to_eci(lat1_new, lon1_new, h1_new),
            self.geodetic_to_eci(lat2_new, lon2_new, h2_new),
            self.geodetic_to_eci(lat3_new, lon3_new, h3_new)
        ]
        for coords in new_state_eci:
            if not self.is_valid_eci(coords):
                new_state = self.find_closest_state(new_state)


        return new_state
    def is_valid_eci(self, coords):

        x, y, z = coords
        distance_from_center = np.linalg.norm([x, y, z])
        return (self.R_E + 500) <= distance_from_center <= (self.R_E + 1000)
    """
    def find_closest_state(self, state):
        #h1, phi1, h2, phi2, h3, phi3 = state
        lat1, lon1, h1, lat2, lon2, h2, lat3, lon3, h3 = state
        closest_state = min(self.state_space, key=lambda s: (abs(s[0]-h1) + abs(s[1]-phi1) + abs(s[2]-h2) + abs(s[3]-phi2) + abs(s[4]-h3) + abs(s[5]-phi3)))
        return closest_state
    """ #will be changed for the new state space
    #

    def geographic_distance(self,s1, s2):
      # info from  states
      lat1, long1, alt1 = s1
      lat2, long2, alt2 = s2

      #
      lat1_rad, long1_rad = np.radians(lat1), np.radians(long1)
      lat2_rad, long2_rad = np.radians(lat2), np.radians(long2)


      R = 6371.0

      # Haversine formula to calculate the distance on the sphere
      delta_lat = lat2_rad - lat1_rad
      delta_long = long2_rad - long1_rad
      a = np.sin(delta_lat / 2)**2 + np.cos(lat1_rad) * np.cos(lat2_rad) * np.sin(delta_long / 2)**2
      c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

      #
      surface_distance = R * c#-----

      #   dist with the alt diff (Euclidean)
      alt_diff = abs(alt2 - alt1)
      total_distance = np.sqrt(surface_distance**2 + alt_diff**2)

      return total_distance


    def is_on_earth(self,position, epsilon=1e-3):#to check wether the current node is a sallite or a ground point while routing
      R_E = 6371
      distance_from_center = np.linalg.norm(position)
      return abs(distance_from_center - R_E) >= epsilon


    def find_closest_state(self, state):
    # min dis
      closest_state = min(self.state_space, key=lambda s: geographic_distance(state, s))
      return closest_state

    """
    def line_of_sight(self, A, B):   # change los calculation computes 2 stattlites in space has los and and another point in space and a ground station .....test with points
        d = distance.euclidean(A, B)
        return d <= 2 * self.R_E
    """#will be replaced
    def julian_date(self,utc_time):

      unix_epoch = datetime(1970, 1, 1, 0, 0, 0, tzinfo=timezone.utc)
      delta_seconds = (utc_time - unix_epoch).total_seconds()
      julian_date = 2440587.5 + delta_seconds / 86400.0
      return julian_date

    def gst_from_julian(self,julian_date):
      T = (julian_date - 2451545.0) / 36525.0
      GST = 280.46061837 + 360.98564736629 * (julian_date - 2451545.0) + 0.000387933 * T**2 - (T**3 / 38710000.0)
      GST = GST % 360.0  # Keep within 0 to 360 degrees
      return np.radians(GST)

    def geodetic_to_eci(self,lat_deg, lon_deg, altitude_km=0, utc_time=None):

      if utc_time is None:
        utc_time = datetime.utcnow().replace(tzinfo=timezone.utc)

      lat = np.radians(lat_deg)
      lon = np.radians(lon_deg)

      R_E = 6378.137

    # Compute the Julian Date from the given UTC time
      jd = self.julian_date(utc_time)

      gst = self.gst_from_julian(jd)

      lon_eci = lon + gst  # Longitude in the inertial frame (ECI)

      x = (R_E + altitude_km) * np.cos(lat) * np.cos(lon_eci)
      y = (R_E + altitude_km) * np.cos(lat) * np.sin(lon_eci)
      z = (R_E + altitude_km) * np.sin(lat)

      return x, y, z

    def los_between_satellites(self,pos1, pos2, earth_radius=6371.0):

      p1 = np.array(pos1)
      p2 = np.array(pos2)

      vector = p2 - p1

      midpoint = (p1 + p2) / 2

      distance_midpoint_to_center = np.linalg.norm(midpoint)

      return distance_midpoint_to_center >= earth_radius



    def line_of_sight(self,satellite_pos, ground_pos, R_E=6371):# ground to sattlite

      satellite_pos = np.array(satellite_pos)
      ground_pos = np.array(ground_pos)

      ground_to_sat = satellite_pos - ground_pos

      ground_distance = np.linalg.norm(ground_pos)

      angle = np.arccos(np.dot(ground_to_sat, ground_pos) / (np.linalg.norm(ground_to_sat) * ground_distance))


      if angle < np.pi / 2:
        return True  # sat is in LoS
      else:
        return False  # No LoS
    def satellite_coverage_check(self,r1, r2): #between sattlites in space with input ECI postions
      Re=6371

      r1 = np.array(r1) #  1st sat (x1, y1, z1)
      r2 = np.array(r2) #pos of the 2 sat (x1, y1, z1)

      # get the Euc dist
      d = np.linalg.norm(r1 - r2)

      # get the min dist-> earth & line (connecting the sats)
      d_min = np.linalg.norm(np.cross(r1, r2)) / d

      # chk if the min dist > earth rad
      return d_min > Re



    def closest_satellite(self, B, satellites):
        return min(satellites, key=lambda s: distance.euclidean(B, s))

    def coverage(self, h, N):
        return 1 - np.exp(-N * h / (2 * (self.R_E + h)))

    def path_loss(self, d, L_0, n, d_0):
        return L_0 * (d / d_0) ** -n

    def received_power(self, P_transmitted, path_loss, l, zeta):
        return P_transmitted * l / path_loss

    def SINR(self, P_received, interference, noise):
        return P_received / (interference + noise)

    def propagation_delay(self, distance):
        return distance / self.c


    def find_route(self,A, B, satellites):
      d_tot = 0
      num_hops = 0
      current_node = A
      visited_satellites = set()

      while True :
        # gwt satellites with a line of sight to the current node, exclude  visited satellites
        if self.is_on_earth(current_node):
          print("on earth")
          los_satellites = [s for s in satellites if self.line_of_sight (current_node, s) and s not in visited_satellites]


        else:
          los_satellites = [s for s in satellites if self.satellite_coverage_check (s, current_node) and s not in
            visited_satellites] #the current node is a sattliete

        if not los_satellites:
            # No forward satellites available, coverage failed
            #raise ValueError("Coverage failed: No forward satellites with line of sight found.")
            break



        # Find the closest satellite to B from the available line-of-sight satellites

        s_hat = self.closest_satellite(B, los_satellites)
        if(s_hat in visited_satellites):
          continue  # skip if the closest satellite is already visited

        # update total dist and incr the nr of hops
        d_tot += distance.euclidean(current_node, s_hat)
        num_hops += 1

        # Mark the curr sat as visited -- no back hoping
        visited_satellites.add(s_hat)

        # Check if there's a line of sight between the chosen satellite and the destination B
        if(self.is_on_earth(B)):

          if self.line_of_sight(s_hat, B):
            d_totaltitude += distance.euclidean(s_hat, B)
            break
        else :
          if self.satellite_coverage_check(s_hat, B):
            d_tot += distance.euclidean(s_hat, B)
            break
        # Move to the next satellite for the next hop
        current_node = s_hat

      return d_tot, num_hops


    def compute_reward(self, state, action, new_state):
        lat1, lon1, h1, lat2, lon2, h2, lat3, lon3, h3 = state
        lat1_new, lon1_new, h1_new, lat2_new, lon2_new, h2_new, lat3_new, lon3_new, h3_new = new_state

        satellite_positions = [
    self.geodetic_to_eci(lat1, lon1, h1),  # First satellite
    self.geodetic_to_eci(lat2, lon2, h2),  # Second satellite
    self.geodetic_to_eci(lat3, lon3, h3) ]

        satellite_positions_new = [
    self.geodetic_to_eci(lat1_new, lon1_new, h1_new),  # First satellite (new)
    self.geodetic_to_eci(lat2_new, lon2_new, h2_new),  # Second satellite (new)
    self.geodetic_to_eci(lat3_new, lon3_new, h3_new)]

        coverage_old = sum(self.coverage(h, self.num_satellites) for h in [h1, h2, h3])
        coverage_new = sum(self.coverage(h, self.num_satellites) for h in [h1_new, h2_new, h3_new])

        L_0 = 1.0  #loss parameters randomly definedc
        n = 2.0
        d_0 = 1.0

        path_loss_old = [self.path_loss(np.sqrt((self.R_E + h)**2 - self.R_E**2), L_0, n, d_0) for h in [h1, h2, h3]]
        path_loss_new = [self.path_loss(np.sqrt((self.R_E + h_new)**2 - self.R_E**2), L_0, n, d_0) for h_new in [h1_new, h2_new, h3_new]]

        P_received_old = [self.received_power(self.P_transmitted, pl, 1, 1) for pl in path_loss_old]
        P_received_new = [self.received_power(self.P_transmitted, pl, 1, 1) for pl in path_loss_new]

        SINR_old = [self.SINR(P, 0, self.N_noise) for P in P_received_old]
        SINR_new = [self.SINR(P, 0, self.N_noise) for P in P_received_new]

        d_tot_old, num_hops_old = self.find_route(self.A, self.B, satellite_positions)
        d_tot_new, num_hops_new = self.find_route(self.A, self.B, satellite_positions_new)

        latency_old = self.propagation_delay(d_tot_old) + num_hops_old * 1  # Assuming L_processing +1
        latency_new = self.propagation_delay(d_tot_new) + num_hops_new * 1

        alpha = 1.0  # Weight for coverage
        beta = 1.0  # Weight for latency
        gamma = 1.0  # Weight for SINR

        reward = alpha * (coverage_new - coverage_old) - beta * (latency_new - latency_old) + gamma * (np.mean(SINR_new) - np.mean(SINR_old))

        return reward

env = SatelliteRoutingEnv()

# Initi Q-
Q = defaultdict(lambda: defaultdict(float))

# hperparams
initial_alpha_lr = 0.1  # initial lr
alpha_decay_rate = 0.99  # decay
min_alpha_lr = 0.01  # min lr
gamma_discount = 0.95  # discount
initial_epsilon = 1.0  # full expolaration then decrease
epsilon_decay_rate = 0.995  # Decay explore
min_epsilon = 0.01  # min explore
num_episodes = 5000


rewards = []
smoothed_rewards = []
q_value_diffs = []
explore_exploit_ratios = []

alpha_lr = initial_alpha_lr
epsilon = initial_epsilon

for episode in range(num_episodes):
    state_idx = env.reset()
    state = env.state_space[state_idx]
    done = False
    episode_reward = 0
    max_diff = 0
    explore_count = 0
    exploit_count = 0

    while not done:
        if np.random.rand() < epsilon:
            explore_count += 1
            action = tuple(env.action_space.sample())  # explore action space
        else:
            exploit_count += 1
            if state not in Q or not Q[state]:
                action = tuple(env.action_space.sample())
            else:
                action = max(Q[state], key=Q[state].get)  # exploit learned values  for un known or un known states we need wxploit

        #  action
        new_state_idx, reward, done, _ = env.step(action)
        new_state = env.state_space[new_state_idx]

        # Update Q-
        #“Q(s,a)←(1−α)Q(s,a)+α\[r+γa′max​Q(s′,a′)\]”
        old_value = Q[state][action]
        future_reward = max(Q[new_state].values(), default=0)
        new_value = old_value + alpha_lr * (reward + gamma_discount * future_reward - old_value)

        max_diff = max(max_diff, abs(new_value - old_value))

        Q[state][action] = new_value

        state = new_state
        episode_reward += reward

    rewards.append(episode_reward)
    q_value_diffs.append(max_diff)
    explore_exploit_ratios.append(explore_count / max(1, exploit_count))

    # Decay lr and explore
    alpha_lr = max(min_alpha_lr, alpha_lr * alpha_decay_rate)
    epsilon = max(min_epsilon, epsilon * epsilon_decay_rate)

    # moving avg for rewar
    if episode >= 100:
        smoothed_rewards.append(np.mean(rewards[-100:]))


plt.plot(rewards)
plt.xlabel('Episode')
plt.ylabel('Reward')
plt.title('Q-learning Rewards Per Episode')
plt.show()

plt.plot(smoothed_rewards)
plt.xlabel('Episode')
plt.ylabel('Smoothed Reward')
plt.title('Smoothed Q-learning Rewards Over Time')
plt.show()

plt.plot(q_value_diffs)
plt.xlabel('Episode')
plt.ylabel('Max Q-value Difference')
plt.title('Q-value Difference Over Time')
plt.show()

plt.plot(explore_exploit_ratios)
plt.xlabel('Episode')
plt.ylabel('Exploration/Exploitation Ratio')
plt.title('Exploration vs Exploitation Over Time')
plt.show()

#berlin and capetown ,    ship in the atlantic ocean ...  explore the ECI coordinates ... validate ....pick the lat and long .....plot the sattlites with ECI , ECEf ....pick a time where ECI   ..... explore who good in at some point in time and then propagate to 10 mins

# Set epsilon to 0 to always exploit the best learned policy
epsilon = 0.0

# Test the trained agent
num_test_episodes = 10
test_rewards = []
learned_positions = []

for episode in range(num_test_episodes):
    state_idx = env.reset()
    state = env.state_space[state_idx]
    done = False
    episode_reward = 0
    episode_positions = []

    while not done:
        if state not in Q or not Q[state]:
            action = tuple(env.action_space.sample())  # Fallback to random if no Q-values
        else:
            action = max(Q[state], key=Q[state].get)  # Exploit the best learned action

        new_state_idx, reward, done, _ = env.step(action)
        new_state = env.state_space[new_state_idx]

        # Record the positions for visualization
        lat1,long1,h1,lat2,long2, h2,lat3,long3 ,h3 = state
        episode_positions.append(((lat1,long1,h1), (lat2,long2, h2), (lat3,long3 ,h3)))

        state = new_state
        episode_reward += reward

    test_rewards.append(episode_reward)
    learned_positions.append(episode_positions)

# Average test reward over the test episodes
average_test_reward = np.mean(test_rewards)
print(f"Average Test Reward: {average_test_reward}")

# Colors for each satellite
colors = ['b', 'orange', 'purple']

# Visualize the learned positions
for episode_idx, episode_positions in enumerate(learned_positions):
    plt.figure(figsize=(8, 6))
    for step_idx, positions in enumerate(episode_positions):
        for satellite_idx, (lat,long, h) in enumerate(positions):

            x,y,z=geodetic_to_eci(lat,long,h)
            plt.scatter(x, y, color=colors[satellite_idx], label=f'Satellite {satellite_idx + 1}' if step_idx == 0 else "", marker='o')

            # Plot the satellite's trajectory over time
            if step_idx > 0:
                prev_lat,prev_long,prev_h = episode_positions[step_idx - 1][satellite_idx]

                prev_x,prev_y,prev_z = geodetic_to_eci(prev_lat,prev_long,prev_h)
                x,y,z = geodetic_to_eci(lat,long,h)
                plt.plot([prev_x, x], [prev_y, y], linestyle='--', color=colors[satellite_idx], alpha=0.7)

    plt.scatter(env.A[0], env.A[2], color='g', marker='s', label='Point A')
    plt.scatter(env.B[0], env.B[2], color='r', marker='x', label='Point B')
    plt.xlabel('X Coordinate (km)')
    plt.ylabel('Height (km)')
    plt.title(f'Learned Satellite Positions - Episode {episode_idx + 1}')
    plt.legend()
    plt.grid(True)
    plt.show()

import matplotlib.pyplot as plt

# Assuming you have recorded these values during training
episodes = list(range(num_episodes))
exploration_rate = [0.9 * (0.99 ** i) for i in episodes]  # Example epsilon decay

# Exploration vs Exploitation Graph
plt.figure(figsize=(10, 5))
plt.plot(episodes, exploration_rate, label='Exploration Rate (ε)')
plt.xlabel('Episodes')
plt.ylabel('Exploration Rate')
plt.title('Exploration Rate over Time')
plt.legend()
plt.show()

"""coverage_values, sinr_values = validate_on_real_data(env, Q)"""

def validate_on_real_data(env, q_table):
    state = env.reset()
    total_reward = 0
    rewards_per_step = []
    sinr_values = []
    coverage_values = []
    eci_positions_history = []
    rewards_per_episode = []

    for episode in range(num_test_episodes):
        state = env.reset()
        done = False
        total_reward = 0
        step = 0

        while not done:
            if state not in Q or not Q[state]:
                action = tuple(env.action_space.sample())
            else:
                action = max(Q[state], key=Q[state].get)  # Exploit learned
            new_state, reward, done, _ = env.step(action)

            # Store positions and SINR for plotting
            state_tuple = env.state_space[state]
            positions = [
                (env.R_E * np.cos(state_tuple[1]), env.R_E * np.sin(state_tuple[1]), state_tuple[0]),
                (env.R_E * np.cos(state_tuple[3]), env.R_E * np.sin(state_tuple[3]), state_tuple[2]),
                (env.R_E * np.cos(state_tuple[5]), env.R_E * np.sin(state_tuple[5]), state_tuple[4])
            ]
            eci_positions_history.append(positions)

            plot_eci_positions([eci_positions_history[-1]], env.A, env.B)  # Plot only the last episode's positions

            # Calculate SINR for plotting
            lat1,long1 ,h1, lat2,long2 ,h2, lat3,long3 ,h3 = state_tuple
            sinr = env.SINR(env.received_power(env.P_transmitted, env.path_loss(env.find_route(env.A, env.B, positions)[0], 10, 2, 1), 0.5, 1), 0, env.N_noise)
            sinr_values.append(sinr)

            d_tot, num_hops = env.find_route(env.A, env.B, positions)
            path_loss = env.path_loss(d_tot, L_0=10, n=2, d_0=1)
            P_received = env.received_power(env.P_transmitted, path_loss, l=0.5, zeta=1)



            coverage = (
            env.coverage(env.state[2],  num_hops) +
            env.coverage(env.state[5],  num_hops) +
            env.coverage(env.state[8],  num_hops)) / env.num_satellites  # Average coverage across satellites
            coverage_values.append(coverage)

            state = new_state
            total_reward += reward
            step += 1

        rewards_per_episode.append(total_reward)

    # Plot the learned ECI positions
    #plot_eci_positions(eci_positions_history, env.A, env.B)
    plot_eci_positions([eci_positions_history[-1]], env.A, env.B)  # Plot only the last episode's positions


    # Plot the SINR values
    plot_sinr(sinr_values)
    plot_cov(coverage_values)

    return rewards_per_episode

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def plot_eci_positions(eci_positions_history, A_eci, B_eci):
    """Plot the ECI positions of satellites and the ground stations A and B."""
    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection='3d')

    # Plot the initial positions of A and B
    ax.scatter(A_eci[0], A_eci[1], A_eci[2], color='blue', label='Station A (Berlin)', s=100)
    ax.scatter(B_eci[0], B_eci[1], B_eci[2], color='red', label='Station B (Cape Town)', s=100)

    # Plot satellite positions at each step
    for step, positions in enumerate(eci_positions_history):
        x, y, z = zip(*positions)
        ax.scatter(x, y, z, label=f'Step {step}', alpha=0.6)

    ax.set_xlabel('X (km)')
    ax.set_ylabel('Y (km)')
    ax.set_zlabel('Z (km)')
    ax.set_title('Learned Positions of Satellites in ECI Coordinates')
    ax.legend()
    plt.show()

def plot_sinr(sinr_values):
    """Plot SINR values over time."""
    plt.figure(figsize=(10, 6))
    plt.plot(sinr_values, marker='o', linestyle='-', color='green', label='SINR')
    plt.xlabel('Time Step')
    plt.ylabel('SINR (dB)')
    plt.title('SINR Values Over Time')
    plt.legend()
    plt.grid(True)
    plt.show()
def plot_cov(cov_values):
    """Plot SINR values over time."""
    plt.figure(figsize=(10, 6))
    plt.plot(cov_values, marker='o', linestyle='-', color='green', label='coverage')
    plt.xlabel('Time Step')
    plt.ylabel('Coverage (dB)')
    plt.title('Coverage Values Over Time')
    plt.legend()
    plt.grid(True)
    plt.show()

validate_on_real_data(env, Q)

"""End of enviroment ,...............start of code trials .-----------------------"""

def line_of_sight(satellite_pos, ground_pos, R_E=6371):#  los_to ground
 #from sattlite to ground with eci x,y,z input npostions
    satellite_pos = np.array(satellite_pos)
    ground_pos = np.array(ground_pos)

    ground_to_sat = satellite_pos - ground_pos

    ground_distance = np.linalg.norm(ground_pos)

    angle = np.arccos(np.dot(ground_to_sat, ground_pos) / (np.linalg.norm(ground_to_sat) * ground_distance))


    if angle < np.pi / 2:
        return True  # sat is in LoS
    else:
        return False  # No LoS

"""Helper functions ----------------------"""

import numpy as np
from datetime import datetime, timezone

def julian_date(utc_time):
    """Convert UTC time to Julian Date."""
    unix_epoch = datetime(1970, 1, 1, 0, 0, 0, tzinfo=timezone.utc)
    delta_seconds = (utc_time - unix_epoch).total_seconds()
    julian_date = 2440587.5 + delta_seconds / 86400.0
    return julian_date

def gst_from_julian(julian_date):
    """Compute Greenwich Sidereal Time from Julian Date."""
    T = (julian_date - 2451545.0) / 36525.0
    # Compute GST in degrees, modulo 360 to stay within bounds
    GST = 280.46061837 + 360.98564736629 * (julian_date - 2451545.0) + 0.000387933 * T**2 - (T**3 / 38710000.0)
    GST = GST % 360.0  # Ensure GST is within [0, 360] degrees
    return np.radians(GST)



def geodetic_to_eci(lat_deg, lon_deg, altitude_km=0, utc_time=None):

      if utc_time is None:
        utc_time = datetime.utcnow().replace(tzinfo=timezone.utc)

      lat = np.radians(lat_deg)
      lon = np.radians(lon_deg)

      R_E = 6378.137

    # Compute the Julian Date from the given UTC time
      jd = julian_date(utc_time)

      gst = gst_from_julian(jd)

      lon_eci = lon + gst  # Longitude in the inertial frame (ECI)

      x = (R_E + altitude_km) * np.cos(lat) * np.cos(lon_eci)
      y = (R_E + altitude_km) * np.cos(lat) * np.sin(lon_eci)
      z = (R_E + altitude_km) * np.sin(lat)

      return x, y, z



def is_on_earth(position, epsilon=1e-3):#to check wether the current node is a sallite or a ground point while routing
    R_E = 6371
    distance_from_center = np.linalg.norm(position)
    return abs(distance_from_center - R_E) >= epsilon

# Example: White Sands Ground Station
utc_time = datetime(2024, 9, 26, 12, 0, 0, tzinfo=timezone.utc)
Latw = 32.38  # Latitude of White Sands
Longw = -106.48  # Longitude of White Sands
alt = 1.2  # Altitude in kilometers (optional)


# Example usage of the function
lat = 52.5200  # Latitude of Berlin (in degrees)
lon = 13.4050  # Longitude of Berlin (in degrees)
altitude = 0.034  # Altitude in kilometers (~34 meters above sea level)


Latc= -33.9249#° (degrees south)
Longc= 18.4241#° (degrees east)
Altc= 0.060 #km (~60 meters above sea level)



Lati= 32.38#° (degrees south)
Longi=  106.48#° (degrees east)

Lats= 67.88#° (degrees east)
Longs=  21.06#° (degrees east)
# Define a specific UTC time
utc_time = datetime(2024, 9, 13, 12, 0, 0, tzinfo=timezone.utc)  # Example UTC time

lat_test=49.78
long_test=9.97
h_test=0

# Convert to ECI coordinates
x, y, z = geodetic_to_eci(lat, lon, altitude, utc_time)
xc, yc, zc = geodetic_to_eci(Latc, Longc, Altc, utc_time)


xs, ys, zs = geodetic_to_eci(Lats, Longs, altitude, utc_time)
xi, yi, zi = geodetic_to_eci(Lati, Longi, Altc, utc_time)
xw, yw, zw = geodetic_to_eci(Latw, Longw, Altc, utc_time)
xt, yt, zt = geodetic_to_eci(lat_test, long_test, h_test, None)


print(f"ECI Coordinates: x = {x:.2f} km, y = {y:.2f} km, z = {z:.2f} km")
print(f"ECI Coordinates: x = {xc:.2f} km, y = {yc:.2f} km, z = {zc:.2f} km")

print(f"ECI Coordinates: x = {xi:.2f} km, y = {yi:.2f} km, z = {zi:.2f} km")#
print(f"ECI Coordinates: x = {xs:.2f} km, y = {ys:.2f} km, z = {zs:.2f} km")

print(f"ECI Coordinates: x = {xw:.2f} km, y = {yw:.2f} km, z = {zw:.2f} km")

print(f"ECI Coordinates: of the zft test x = {xt:.2f} km, y = {yt:.2f} km, z = {zt:.2f} km")

"""Routing function on the test ... Function for test .....outside the env

function with self outside the env just for testing

def find_route(self,A, B, satellites):# create a test case of routing scenario ...to test 3 satts ,5 statts , 6 stats, add the no coverage condition ,,,then terminate ....
    d_tot = 0
    num_hops = 0
    current_node = A
    visited_satellites = set()

    while True :
        # gwt satellites with a line of sight to the current node, exclude  visited satellites
        if is_on_earth(current_node):
          los_satellites = [s for s in satellites if self.line_of_sight (current_node, s) and s not in visited_satellites]

          if not los_satellites:
            # No forward satellites available, coverage failed
            raise ValueError("Coverage failed: No forward satellites with line of sight found.")
            continue
        else:
          los_satellites = [s for s in satellites if self.satellite_coverage_check (s, current_node) and s not in
            visited_satellites] #the current node is a sattliete





        # Find the closest satellite to B from the available line-of-sight satellites

        s_hat = self.closest_satellite(B, los_satellites)
        if(s_hat in visited_satellites):
          continue  # Skip if the closest satellite is already visited

        # Update total dist and incr the nr of hops
        d_tot += distance.euclidean(current_node, s_hat)
        num_hops += 1

        # Mark the curr sat as visited -- no back hoping
        visited_satellites.add(s_hat)

        # Check if there's a line of sight between the chosen satellite and the destination B
        if(is_on_earth(B)):

          if self.line_of_sight(s_hat, B):
            d_totaltitude += distance.euclidean(s_hat, B)
            break
        else :
          if self.satellite_coverage_check(s_hat, B):
            d_tot += distance.euclidean(s_hat, B)
            break
        # Move to the next satellite for the next hop
        current_node = s_hat

    return d_tot, num_hops
"""

import numpy as np
def satellite_coverage_check(r1, r2):
    Re=6371


    r1 = np.array(r1) # pos of the 1 sat (x1, y1, z1)
    r2 = np.array(r2) #pos of the 2 sat (x1, y1, z1)

    # get the Euc dist
    d = np.linalg.norm(r1 - r2)

    # get the min dist-> earth & line (connecting the sats)
    d_min = np.linalg.norm(np.cross(r1, r2)) / d

    # chk if the min dist > earth rad
    return d_min > Re

r1 = (7000, 0, 0)  #
r2 = (7000, 7000, 0)
Re = 6371

r1 = (3000, 2000, 0)  #
r2 = (3000, 7000, 0)
Re = 6371
#those examples are using absolute ECI x,y,z coordinates
can_see_each_other = satellite_coverage_check(r1, r2)
print("Satellites can see each other:", can_see_each_other)

def generate_satellites(n, altitude_range=(500, 1000), Re=6371):

    #given alth h generate rand sat pos


    satellites = []
    for _ in range(n):
        altitude = np.random.uniform(*altitude_range)  # Rand alt
        radius = Re + altitude

        #rand spheric coord
        phi = np.random.uniform(0, np.pi * 2)  # long
        theta = np.random.uniform(0, np.pi)  # lat

        #  spherical to Cartesian
        x = radius * np.sin(theta) * np.cos(phi)
        y = radius * np.sin(theta) * np.sin(phi)
        z = radius * np.cos(theta)

        satellites.append((x, y, z))

    return satellites


def check_los_between_satellites(satellites, Re):#between sattlite genrated pairs
    """
    Check LoS between all pairs of sats
    x y z podtiond
    """
    n = len(satellites)

    for i in range(n):
        for j in range(i + 1, n):
            can_see_each_other = satellite_coverage_check(satellites[i], satellites[j])
            #print(f"Satellite {i+1} and Satellite {j+1}: {'LoS Available' if can_see_each_other else 'No LoS'}")
            return can_see_each_other  #true or F

Re = 6371

# sc1 1: 3 Sats
satellites_3 = generate_satellites(3)
c=check_los_between_satellites(satellites_3, Re)

print(c,"\n")

# sc2 2: 4 Sats
satellites_4 = generate_satellites(4)
print(satellites_4)
c=check_los_between_satellites(satellites_4, Re)

print(c,"\n")

# sc3 3: 5 Sats
satellites_5 = generate_satellites(5)
c=check_los_between_satellites(satellites_5, Re)
print(c,"\n")

"""code im still try8ing"""

import numpy as np

def generate_circular_orbit_satellites(n, altitude, Re=6371):

    #Generate sats pos in a circular orbit


    satellites = []
    radius = Re + altitude

    #fixed lat  for  orbit (equatorial here)
    latitude = 0  # eq orbit-> (0 degrees latitude)
    theta = np.radians(90 - latitude)  #  latitude to polar(rad)

    #  even ditro along the orbit vary-> long (phi)
    for i in range(n):
        #
        longitude = i * (360 / n)
        phi = np.radians(longitude)  # long 2rads

        #  spherical  (radius, theta, phi) to Cartesian (x, y, z)
        x,y,z=geodetic_to_eci(latitude, longitude, altitude, None)


        satellites.append((x, y, z))

    return satellites

# implememnted and integrated above thats only the solo trial
def check_los_between_satellites(satellites, Re):
    """
    Check LoS between all pairs of satellites and print the results.

    Parameters:
    satellites (list): List of satellite positions as tuples (x, y, z).
    Re (float): Earth's radius in kilometers.
    """
    n = len(satellites)
    print(f"Checking Line of Sight between {n} satellites:")
    for i in range(n):
        for j in range(i + 1, n):
            can_see_each_other = satellite_coverage_check(satellites[i], satellites[j])
            print(f"Satellite {i+1} and Satellite {j+1}: {'LoS Available' if can_see_each_other else 'No LoS'}")

Re = 6371  #
altitude = 100

# Scenario 1: 3 sat in a circ orbit
satellites_3 = generate_circular_orbit_satellites(3, altitude)
check_los_between_satellites(satellites_3, Re)

print("\n")

# sc 2: 4 sat in a circ orbit
satellites_4 = generate_circular_orbit_satellites(4, altitude)
check_los_between_satellites(satellites_4, Re)

print("\n")

# sc 3: 5 sat in a circ orbit
satellites_5 = generate_circular_orbit_satellites(5, altitude)
check_los_between_satellites(satellites_5, Re)

"""LOs to ground not used anymore"""

def los_to_ground(satellite_position, ground_position, R_E):#changed to line of ######################################################################################sight bellow cuz its more accurate
      # get pos (x, y, z) for sat and gp
      x_s, y_s, z_s = satellite_position
      x_g, y_g, z_g = ground_position

      # vec  gr pt to sat
      v_gs = np.array([x_s - x_g, y_s - y_g, z_s - z_g])

      # vec  Earth cent to gr pt
      r_g = np.array([x_g, y_g, z_g])

      # dot v_gs and r_g
      dot_product = np.dot(v_gs, r_g)

      # mag of v_gs and r_g
      norm_v_gs = np.linalg.norm(v_gs)
      norm_r_g = np.linalg.norm(r_g)

      # get cos of  between v_gs and r_g
      cos_theta = dot_product / (norm_v_gs * norm_r_g)

      # If cos(theta) > 0, sat is in LoS (above horizon)
      if cos_theta > 0:
        return True  # sat  above the horizon
      else:
        return False  # sat  below  horizon (no LoS)

# Example ECI coordinates for satellite and ground point
satellite_position = (7000, 0, 1000)  # Satellite in ECI coordinates
ground_position = (6371, 0, 0)  # Ground point on the equator

# Earth radius in km
R_E = 6371


r_s = (7000, 7000, 0)  # Example satellite position
r_g = (6371, 0, 0)     # Example ground position(equatorial point)


in_los = los_to_ground(satellite_position, ground_position, R_E)
print("Satellite is in LoS:", in_los)


in_los = los_to_ground(r_s, r_g, R_E)
print("Satellite is in LoS in case 2:", in_los)

"""end of losssssssss to ground ...............note a degraded fujction

under trial not integrated yet
"""

import numpy as np

def geographic_distance(s1, s2):
    # info from  states
    lat1, long1, alt1 = s1
    lat2, long2, alt2 = s2

    #
    lat1_rad, long1_rad = np.radians(lat1), np.radians(long1)
    lat2_rad, long2_rad = np.radians(lat2), np.radians(long2)


    R = 6371.0

    # Haversine formula to calculate the distance on the sphere
    delta_lat = lat2_rad - lat1_rad
    delta_long = long2_rad - long1_rad
    a = np.sin(delta_lat / 2)**2 + np.cos(lat1_rad) * np.cos(lat2_rad) * np.sin(delta_long / 2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

    #
    surface_distance = R * c#-----

    #   dist with the alt diff (Euclidean)
    alt_diff = abs(alt2 - alt1)
    total_distance = np.sqrt(surface_distance**2 + alt_diff**2)

    return total_distance


def find_closest_state(self, state):
    # min dis
    closest_state = min(self.state_space, key=lambda s: geographic_distance(state, s))
    return closest_state

#  (lat, long, alt)

def find_closest_state(state_space,state):
    # min dis
    closest_state = min(state_space, key=lambda s: geographic_distance(state, s))
    return closest_state
state_space = [
    (10.0, 20.0, 500.0),  #  sat 1
    (15.0, 30.0, 550.0),  # sat 2
    (20.0, 40.0, 600.0),  # sat 3
    (25.0, 50.0, 650.0)   # sat 4
]

#  curr state to find the closest to
current_state = (18.0, 35.0, 570.0)



#
closest_state = find_closest_state(state_space, current_state)
print("Closest state:", closest_state)

"""a trial function will be intergrated above ----------------------------





"""

from skyfield.api import Topos, load   #chatgbt hahaha
import numpy as np

def lat_long_alt_to_eci(latitude, longitude, altitude, time=None):
    # Load time scale and define the current time if not provided
    ts = load.timescale()
    time = time if time else ts.now()

    # Load ephemeris data for Earth
    eph = load('de421.bsp')  # 'de421' ephemeris file for astronomical calculations
    earth = eph['earth']

    # Define the observer location using latitude, longitude, and altitude
    location = Topos(latitude_degrees=latitude, longitude_degrees=longitude, elevation_m=altitude)

    # Compute the position in the ECI frame
    position = (earth + location).at(time).position.km  # Position in kilometers

    # Convert to meters
    x, y, z = np.array(position) * 1000  # Convert from km to meters
    return x, y, z

# Example usage
latitude = 45.0  # in degrees
longitude = -75.0  # in degrees
altitude = 400000  # in meters (400 km above the Earth's surface)

x, y, z = lat_long_alt_to_eci(latitude, longitude, altitude)
print(f"ECI Coordinates: x = {x:.2f} m, y = {y:.2f} m, z = {z:.2f} m")

from scipy.spatial import distance

def closest_satellite(B, satellites):
        return min(satellites, key=lambda s: distance.euclidean(B, s))

def find_route(A, B, satellites):
    d_tot = 0
    num_hops = 0
    current_node = A
    visited_satellites = set()

    while True :
        # gwt satellites with a line of sight to the current node, exclude  visited satellites
        if is_on_earth(current_node):
          print("on earth")
          los_satellites = [s for s in satellites if line_of_sight (current_node, s) and s not in visited_satellites]


        else:
          los_satellites = [s for s in satellites if satellite_coverage_check (s, current_node) and s not in
            visited_satellites] #the current node is a sattliete

        if not los_satellites:
            # No forward satellites available, coverage failed
            #raise ValueError("Coverage failed: No forward satellites with line of sight found.")
            break



        # Find the closest satellite to B from the available line-of-sight satellites

        s_hat = closest_satellite(B, los_satellites)
        if(s_hat in visited_satellites):
          continue  # skip if the closest satellite is already visited

        # update total dist and incr the nr of hops
        d_tot += distance.euclidean(current_node, s_hat)
        num_hops += 1

        # Mark the curr sat as visited -- no back hoping
        visited_satellites.add(s_hat)

        # Check if there's a line of sight between the chosen satellite and the destination B
        if(is_on_earth(B)):

          if line_of_sight(s_hat, B):
            d_totaltitude += distance.euclidean(s_hat, B)
            break
        else :
          if satellite_coverage_check(s_hat, B):
            d_tot += distance.euclidean(s_hat, B)
            break
        # Move to the next satellite for the next hop
        current_node = s_hat

    return d_tot, num_hops

# Example test case with mock functions and satellites in ECI (x, y, z) coordinates
A = geodetic_to_eci(52.52, 13.41)  # Berlin
B = geodetic_to_eci(-33.92, 18.42)  # Cape Town

#satellites_3=generate_satellites(3)
#satellites_3 = generate_circular_orbit_satellites(3, 1000)
#satellites_5 = generate_circular_orbit_satellites(5, 600)
#satellites_6 = generate_satellites(6)


 # Replace with actual satellite ECI positions

# Run the routing function with mock inputs
#d_tot, num_hops = find_route(A, B, satellites_3)
#print(f"Total distance: {d_tot}, Number of hops: {num_hops}")

import numpy as np

def generate_test_cases(Re):

    test_cases = []

    # 1. Satellites close together but with coverage
    r1_close_cover = np.array([Re + 500, 0, 0])  # 500 units above Earth surface
    r2_close_cover = np.array([Re + 500, 500, 0])
    test_cases.append((r1_close_cover, r2_close_cover, "Close together, with coverage"))

    # 2. Satellites far apart with coverage
    r1_far_cover = np.array([Re + 500, 0, 0])
    r2_far_cover = np.array([0, Re + 500, 500])
    test_cases.append((r1_far_cover, r2_far_cover, "Far apart, with coverage"))

    # 3. Satellites close together without coverage
    r1_close_no_cover = np.array([Re + 100, 0, 0])  # Closer to Earth
    r2_close_no_cover = np.array([Re + 100, 100, 0])
    test_cases.append((r1_close_no_cover, r2_close_no_cover, "Close together, with coverage"))

    # 4. Satellites far apart without coverage
    r1_far_no_cover = np.array([Re + 100, 0, 0])
    r2_far_no_cover = np.array([0, Re + 100, 100])
    test_cases.append((r1_far_no_cover, r2_far_no_cover, "Far apart, without coverage"))

    return test_cases

# Example usage
Re = 6371  # Earth's radius in kilometers
test_cases = generate_test_cases(Re)

for r1, r2, description in test_cases:
    coverage = satellite_coverage_check(r1, r2)
    print(f"{description}: Coverage {'exists' if coverage else 'does not exist'}")

import numpy as np

# Constants
Re = 6371  # Radius of Earth in kilometers
altitude = 550  # Altitude of satellites in kilometers

# Ground station positions (latitude, longitude) in degrees
berlin_lat, berlin_lon = 52.52, 13.405
cape_town_lat, cape_town_lon = -33.9249, 18.4241



def line_of_sight(satellite_pos, ground_pos, R_E=6371):

    satellite_pos = np.array(satellite_pos)
    ground_pos = np.array(ground_pos)

    ground_to_sat = satellite_pos - ground_pos

    ground_distance = np.linalg.norm(ground_pos)

    angle = np.arccos(np.dot(ground_to_sat, ground_pos) / (np.linalg.norm(ground_to_sat) * ground_distance))


    if angle < np.pi / 2:
        return True  # sat is in LoS
    else:
        return False  # No LoS
berlin_pos = geodetic_to_eci(berlin_lat, berlin_lon, 0)
cape_town_pos = geodetic_to_eci(cape_town_lat, cape_town_lon, 0)


num_satellites = 5
satellites_in_los_berlin = []
satellites_in_los_cape_town = []

for _ in range(num_satellites):
    sat_lat = np.random.uniform(-90, 90)
    sat_lon = np.random.uniform(-180, 180)
    satellite_pos = geodetic_to_eci(sat_lat, sat_lon, altitude)

    if line_of_sight(satellite_pos, berlin_pos):
        satellites_in_los_berlin.append((sat_lat, sat_lon, altitude))

    if line_of_sight(satellite_pos, cape_town_pos):
        satellites_in_los_cape_town.append((sat_lat, sat_lon, altitude))

# Print satellites in LoS for Berlin and Cape Town
print("Satellites in LoS with Berlin:")
for lat, lon, alt in satellites_in_los_berlin:
    print(f"Latitude: {lat:.2f}, Longitude: {lon:.2f}, Altitude: {alt} km")

print("\nSatellites in LoS with Cape Town:")
for lat, lon, alt in satellites_in_los_cape_town:
    print(f"Latitude: {lat:.2f}, Longitude: {lon:.2f}, Altitude: {alt} km")

d_tot, num_hops = find_route(berlin_pos, cape_town_pos, satellites_in_los_berlin)
print(f"Total distance: {d_tot}, Number of hops: {num_hops}")

d_tot, num_hops = find_route(berlin_pos, cape_town_pos, satellites_in_los_cape_town)
print(f"Total distance: {d_tot}, Number of hops: {num_hops}")

def gen_sats_rand_lat_long(altitude,num_satellites):
    satellites_pos = []
    for _ in range(num_satellites):

      sat_lat = np.random.uniform(-90, 90)
      sat_lon = np.random.uniform(-180, 180)
      sat_pos = geodetic_to_eci(sat_lat, sat_lon, altitude)
      satellites_pos.append(sat_pos)
    return satellites_pos


sat_gen_3=gen_sats_rand_lat_long(550,5)
d_tot, num_hops = find_route(berlin_pos, cape_town_pos, sat_gen_3)
print(f"Total distance: {d_tot}, Number of hops: {num_hops}")

import numpy as np
from skyfield.api import Topos, load

# Define Earth's radius in km
R_E = 6371.0

# Function to convert geodetic (lat, long, alt) to ECI (x, y, z)
def geodetic_to_eci_sky(lat, lon, alt, ts):
    earth = load('de421.bsp')['earth']
    location = Topos(latitude_degrees=lat, longitude_degrees=lon, elevation_m=alt * 1000)
    t = ts.now()
    position = (earth + location).at(t).position.km
    return np.array(position)

# Test Berlin and Cape Town positions
ts = load.timescale()
berlin = geodetic_to_eci_sky(52.5200, 13.4050, 0, ts)  # Berlin (lat, lon, alt)
cape_town = geodetic_to_eci_sky(-33.9249, 18.4241, 0, ts)  # Cape Town (lat, lon, alt)

# Check if Berlin and Cape Town are "on the ground"
berlin_is_ground = is_on_earth(berlin)
cape_town_is_ground = is_on_earth(cape_town)

print("Berlin ECI Position:", berlin)
print("Is Berlin on the ground:", berlin_is_ground)
print("Cape Town ECI Position:", cape_town)
print("Is Cape Town on the ground:", cape_town_is_ground)